import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { IBM_Plex_Mono } from 'next/font/google';

const ibmPlexMonoSans = IBM_Plex_Mono({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const ibmPlexMonoMono = IBM_Plex_Mono({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "⚡ MCP Chat",
  description: "Generated by create next app",
  icons:{
    icon: [
      {media: '(prefers-color-scheme: dark)',
      url:("/favicon-dark.ico")},
      {media: '(prefers-color-scheme: light)',
      url:("/favicon-light.ico")}
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ibmPlexMonoSans.variable} ${ibmPlexMonoMono.variable} antialiased font-mono`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <TooltipProvider>
            {children}
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
