import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ThemeToggle } from "@/components/ui/theme-toggle";
import { TooltipProvider } from "@/components/ui/tooltip";
import localFont from 'next/font/local';

const apfelGrotezk = localFont({
  src: [
    {
      path: '../public/font/ApfelGrotezk-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/font/ApfelGrotezk-Mittel.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/font/ApfelGrotezk-Fett.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-apfel-grotezk',
});

const serverMono = localFont({
  src: '../public/font/ServerMono-Regular.woff2',
  variable: '--font-server-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${apfelGrotezk.variable} ${serverMono.variable} antialiased font-mono`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <div className="absolute top-4 right-4 z-50">
              <ThemeToggle />
            </div>
            {children}
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
